import { writeFileSync } from 'fs';
import { readFileSync } from 'fs';
import { existsSync } from 'fs';
import { logger } from '../utils/logger.js';

export async function initCommand(options: { output: string }): Promise<void> {
  const outputPath = options.output;

  if (existsSync(outputPath)) {
    logger.warn({ path: outputPath }, 'Config file already exists');
    process.exit(1);
  }

  const defaultConfig = {
    name: 'default-sync',
    github: {
      owner: 'your-org',
      repo: 'your-repo',
    },
    jira: {
      projectKey: 'PROJ',
    },
    mappings: {
      status: {
        'To Do': 'todo',
        'In Progress': 'in_progress',
        'Done': 'done',
      },
      users: {
        // 'github-username': 'jira-account-id',
      },
      fields: {
        // 'github-field': 'jira-field',
      },
      ignoreStatuses: ['Won\'t Fix'],
      ignoreLabels: ['wontfix'],
    },
    syncPriority: 'timestamp',
    syncComments: true,
    syncLabels: true,
    syncAssignees: true,
  };

  const yamlContent = `# GitHub ↔ Jira Sync Configuration
# Generated by: sync init

name: ${defaultConfig.name}
github:
  owner: ${defaultConfig.github.owner}
  repo: ${defaultConfig.github.repo}
jira:
  projectKey: ${defaultConfig.jira.projectKey}
mappings:
  status:
${Object.entries(defaultConfig.mappings.status)
  .map(([k, v]) => `    "${k}": "${v}"`)
  .join('\n')}
  users: {}
  fields: {}
  ignoreStatuses:
${defaultConfig.mappings.ignoreStatuses?.map((s) => `    - "${s}"`).join('\n') || '    []'}
  ignoreLabels:
${defaultConfig.mappings.ignoreLabels?.map((l) => `    - "${l}"`).join('\n') || '    []'}
syncPriority: ${defaultConfig.syncPriority}
syncComments: ${defaultConfig.syncComments}
syncLabels: ${defaultConfig.syncLabels}
syncAssignees: ${defaultConfig.syncAssignees}
`;

  writeFileSync(outputPath, yamlContent, 'utf-8');
  logger.info({ path: outputPath }, 'Created sync configuration file');
  console.log(`✅ Created sync configuration at: ${outputPath}`);
  console.log('📝 Please edit the file with your GitHub and Jira details');
}

